name: date_util
description: A simple dart API with a complete set of date helper methods
             not available in the DateTime API hence, production is
             made easier when working with dates.
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: ^1.17.11
